export const QUERY_INSURE_INFO = 'QUERY_INSURE_INFO';
export const QUERY_PRODUCT_INFO = 'QUERY_PRODUCT_INFO';
export const SET_KEFU_VISIBLE = 'SET_KEFU_VISIBLE';
export const CHECK_INSURE = 'CHECK_INSURE';